In [1]:
import numpy as np

In [4]:
temperaturas = np.random.uniform(15,40,30)
temperaturas

array([29.6218468 , 36.76317254, 18.76199672, 25.59290275, 18.84269924,
       32.53455558, 22.73171384, 34.59627291, 38.24332789, 32.79803915,
       30.74739472, 39.66669455, 36.43904582, 35.21324875, 36.94385781,
       34.99244881, 34.0081407 , 26.40168378, 36.84496082, 30.28537191,
       22.33367608, 25.30673819, 32.18886635, 35.95327998, 32.31519531,
       25.35599046, 34.52737773, 32.45258001, 37.88237028, 35.9348288 ])

In [6]:
matriz_temp = temperaturas.reshape(5,6)
matriz_temp

array([[29.6218468 , 36.76317254, 18.76199672, 25.59290275, 18.84269924,
        32.53455558],
       [22.73171384, 34.59627291, 38.24332789, 32.79803915, 30.74739472,
        39.66669455],
       [36.43904582, 35.21324875, 36.94385781, 34.99244881, 34.0081407 ,
        26.40168378],
       [36.84496082, 30.28537191, 22.33367608, 25.30673819, 32.18886635,
        35.95327998],
       [32.31519531, 25.35599046, 34.52737773, 32.45258001, 37.88237028,
        35.9348288 ]])

# Encuentra:
# - La temperatura máxima por semana
# - El día (índice) en que ocurrió la temperatura máxima por semana
# - La semana con mayor temperatura global

# - La temperatura máxima por semana

In [7]:
max_semana = np.max(matriz_temp,axis=1)
max_semana

array([36.76317254, 39.66669455, 36.94385781, 36.84496082, 37.88237028])

# - El día (índice) en que ocurrió la temperatura máxima por semana

In [9]:
indice_max_semana = np.argmax(matriz_temp,axis=1)
indice_max_semana + 1

array([2, 6, 3, 1, 5])

# - La semana con mayor temperatura global

In [13]:
semana_max_global = np.argmax(max_semana)
semana_max_global + 1

np.int64(2)

# 2do ejercicio

In [14]:
# Paso 1: Genera una matriz de 10 alumnos x 3 exámenes (notas aleatorias entre 0 y 20)
notas = np.random.randint(0, 21, size=(10, 3))
notas

array([[19, 12,  3],
       [17,  7,  5],
       [20,  8, 10],
       [ 2, 19,  2],
       [ 9,  3, 12],
       [17, 11,  0],
       [16, 20, 18],
       [15, 14,  9],
       [16, 13,  6],
       [20, 15,  8]])

# Encuentra:


*  El alumno con el mejor promedio
*  El examen donde el promedio general fue más bajo
* Ordena a los alumnos según su nota en el primer examen (índice 0)
